# -*- coding: utf-8 -*-
"""AI__exam06_Iris_classfication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojZ0o5t3480SC9TAYRc1XGMUL2muCHJj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

iris = load_iris()
print(type(iris))
print(iris.keys())

iris.data.shape

iris.feature_names

iris.target

iris.target_names

iris_dataframe = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_dataframe.head()

pd.plotting.scatter_matrix(iris_dataframe, c=iris.target,
                           figsize=(8, 8), s=20, marker='o', alpha=0.3)
plt.show()

x = iris.data
y = iris.target.reshape(-1, 1)
print(x.shape)
print(y.shape)

from sklearn.preprocessing import OneHotEncoder
# sparse_output True일 경우 (위치) 값으로 나옴 False일 경우 행렬로만 나옴
encoder = OneHotEncoder(sparse_output=False)
encoded_y = encoder.fit_transform(y)
print(encoded_y)

X_train, X_test, Y_train, Y_test = train_test_split(x, encoded_y, test_size=0.2)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

fit_hist = model.fit(X_train, Y_train, epochs=128, batch_size=10)

score = model.evaluate(X_test, Y_test)
print(score)

plt.plot(fit_hist.history['accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.show()