# -*- coding: utf-8 -*-
"""AI__exam07_classfication_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xvc2JmSjozY0HfMa-GY6ceBO9zmqXdR0
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

# 0 ~ 59999의 랜덤 인덱스
my_sample = np.random.randint(0, X_train.shape[0])
print(my_sample)
print(Y_train[my_sample])
plt.imshow(X_train[my_sample], cmap='gray')
plt.show()
# print(X_train[my_sample])

# 위의 숫자를 10개의 인덱스와 같으면 해당 list의 인덱스가 1
y_train = to_categorical(Y_train)
y_test = to_categorical(Y_test)
print(y_train.shape)
print(y_test.shape)
print(y_train[my_sample])

# 신경망은 1차원으로 펼친걸 좋아해서 28x28보단 784를 좋아함
# reshape는 다차원 리스트를 1차원 리스트로 펼치는 함수
x_train = X_train.reshape(60000, 784)
x_test = X_test.reshape(10000, 784)
# print(x_train[5000])
# print(X_train[5000])

# 색상은 8비트라서 255로 나눔
# 또한 입력값의 범위를 낮추기 위해서
x_train = x_train / 255
x_test = x_test / 255
# print(x_train.shape)
# print(x_train[5000])

model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# model training 하는 곳
fit_hist = model.fit(x_train,
                     y_train,
                     epochs=15,
                     batch_size=512,
                     validation_split=0.2)

plt.plot(fit_hist.history['loss'], label='Training Loss')
plt.plot(fit_hist.history['val_loss'], label='Validation Loss')
plt.legend()
plt.show()

plt.plot(fit_hist.history['accuracy'], label='Training Accuracy')
plt.plot(fit_hist.history['val_accuracy'], label='Validation Accuracy')
# 과적합(Overfitting)으로 인해 acc와 val_acc의 차이가 더 이상 좁혀지지 않음
plt.legend()
plt.show()

score = model.evaluate(x_test, y_test)
print('Final test set accuracy', score[1])

