# -*- coding: utf-8 -*-
"""AI__exam_03_keras_xor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDImFqvgVOagkZZRSHQMJKfHA7JuBW6E
"""

# https://itwiki.kr/w/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5

import numpy as np
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt

traning_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target_data = np.array([[0], [1], [1], [0]])

model = Sequential()
model.add(Dense(32 ,input_dim = 2, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss='mse', optimizer='adam', metrics=['binary_accuracy'])
model.summary()

"""2차원으론 도저히 XOR 함수를 만들 수가 없음

32차원이라는 차원으로 확장해서 XOR함수를 만듦

AND, OR는 2차원의 선으로 구분해서 만들 수가 있음
"""

fit_hist = model.fit(traning_data, target_data, epochs=500, verbose=1)

print(model.predict(np.array([[1, 0]])))

plt.plot(fit_hist.history['loss'])
plt.show()

